In [1]:
import torch

In [2]:
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [5]:
torch.ones(3, dtype=torch.float32)

tensor([1., 1., 1.])

In [6]:
torch.tensor([3.5,2.5])

tensor([3.5000, 2.5000])

In [7]:
torch.rand(3,3)

tensor([[0.9864, 0.1496, 0.3491],
        [0.4781, 0.4545, 0.4387],
        [0.8067, 0.9878, 0.0201]])

In [8]:
torch.rand(2,2) + torch.rand(2,2)

tensor([[1.7785, 1.1708],
        [1.0558, 1.4521]])

In [10]:
x = torch.rand(4,3)
print(x)
x[:,0]

tensor([[0.2073, 0.0245, 0.6196],
        [0.2204, 0.8855, 0.6769],
        [0.2678, 0.3489, 0.6105],
        [0.2787, 0.7401, 0.1244]])


tensor([0.2073, 0.2204, 0.2678, 0.2787])

In [12]:
import numpy as np 
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)
a.add_(1)
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [15]:
a = np.ones(6)
print(a)
b = torch.from_numpy(a)
b

[1. 1. 1. 1. 1. 1.]


tensor([1., 1., 1., 1., 1., 1.], dtype=torch.float64)

In [19]:
a += 1
print(a)
b

[5. 5. 5. 5. 5. 5.]


tensor([5., 5., 5., 5., 5., 5.], dtype=torch.float64)